### ISSUE TITLE
Custom ipfs gateway and JSON Metadata missing

### ISSUE THREAD

**Issue by borispoehland** [ElvenTools/elven-tools-cli#5]
Hello @juliancwirko and thanks a lot for this awesome tool.

I created my first test collection under [this](https://devnet-explorer.elrond.com/accounts/erd1qqqqqqqqqqqqqpgq9q2sk3unpl96fv73hwk5qzpqyf8dy9p62j6qy45azr) address.

My images and metadata are [here](https://gateway.pinata.cloud/ipfs/Qmd4Y4DtWRVSKzMDtPxPgGGpfeQ8bJKYR1pgxxVzBU5S8h). 

Hence I used `Qmd4Y4DtWRVSKzMDtPxPgGGpfeQ8bJKYR1pgxxVzBU5S8h` as my ipfs base path when I set up the contract.

However, when having minted an NFT, not `gateway.pinata.cloud` is taken, but `ipfs.io`. One can see this [here](https://devnet-explorer.elrond.com/nfts/HEW-0fc18e-01).

Besides, also when looking [at the mint](https://devnet-explorer.elrond.com/nfts/HEW-0fc18e-01), the `1.json` file is not listed as asset, but instead the image (`1.png`) is listed twice.

Appreciate your help and thanks!

**Comment by borispoehland** [comment]
Regarding the ipfs, I found a solution by just uploading directly to ipfs. 

[Here](https://devnet-explorer.elrond.com/nfts/HEW-4e4e00-01) is an updated example, and when clicking the ipfs link, one can see that the image is now there!

The only thing that still doesn't seem to work is, that the metadata JSON file is linked as asset.

As an example, [ElrondApes](https://explorer.elrond.com/nfts/EAPES-8f3c1f-7e) has the JSON file linked under assets, while in my case we again have 2 assets, but both point to the image

**Comment by borispoehland** [comment]
Can it be that the metadata problem is because according to the [docs](https://docs.elrond.com/developers/nft-tokens/), the metadata field should have the syntax: `metadata:ipfsCID/fileName.json;tags:tag1,tag2,tag3`, while in [your contract](https://github.com/juliancwirko/elven-nft-minter-sc/blob/c186dce412b1c4afdd9f4077dccbb431fb1f2585/src/lib.rs#L583) the tags come **before** the metadata-statement? 

So in your contract the syntax is: `tags:tag1,tag2,tag3;metadata:ipfsCID/fileName.json`, which is opposite to the docs

**Comment by juliancwirko** [comment]
Elven tools smart contract doesn't add the json files to the assets/uris (at least not yet). The place for the metadata json file is in the NFT's attributes. It is base64 encoded there. The json in the assets is something custom to the marketplace. I have some more about it here: https://github.com/juliancwirko/elven-nft-minter-sc/issues/3

Regarding IPFS, what is essential is only the CID and elven tools smart contract ads the `ipfs://` schema and additionally, the `https://ipfs.io.ipfs/` gateway, which is the most popular, probably even not needed. You can use any ipfs gateway. This doesn't;t matter. What matters is your base CID. Check the: https://ipfs.github.io/public-gateway-checker/ there is a lot of them.

The order of tags and metadata in the attributes doesn't matter.

**Comment by borispoehland** [comment]
@juliancwirko so if I understood it correct, there is no need for a dedicated metadata file, because the metadata is already stored along with the NFT.

That leaves the question open for me, how can one query this metadata?

**Comment by juliancwirko** [comment]
The marketplaces are forcing this probably because it is simpler for them to get the JSON file, but I am not sure why because they can do the same with an additional small step to decode the base64 and get the primary metadata file from attributes. In this single metadata file in attributes, you can have uris to many other json files if needed. IMO this is the cleaner solution because we can leave the assets field for real assets, like images, music, video, etc. But I am probably missing something. Maybe there were some changes in how the API service work. I need to double-check that.

The Elrond API service populates the data from json file and creates the `metadata` entry (https://devnet-api.elrond.com/#/nfts/NftController_getNft see example value structure), so you can use that, but I think this is done asynchronously with some delayed worker to be more performant, so I believe it won't be there immediately after creating the NFT token. And of course, the path to the file and the structure should be valid.

The second option would be to get the data directly from the ipfs using the attributes field, maybe with some custom caching to serve it faster.

**Comment by borispoehland** [comment]
@juliancwirko Thank you so much.

I inserted my token identifier on the link you provided, got `bWV0YWRhdGE6UW1WRHlKWHRGQlZYZW9iQ3p6dWRpNEFuS0tRUXJaVThzY29zalcyU0hHeTdnbi8yLmpzb24=` as attribute, which base64-decoded gave me `QmVDyJXtFBVXeobCzzudi4AnKKQQrZU8scosjW2SHGy7gn/2.json`, the ipfs-link to my metadata.

In your second paragraph you were basically saying that in the next time, they will replace the base64-encoded **path to** my metadata with the actual metadata itself?

**Comment by juliancwirko** [comment]
Yes, this is how it should work, but I checked it some time ago. There is quite a lot going on in the API service repository. I will add a to-do item to double-check it again to ensure that the metadata is created and other stuff, like media links, populated based on the nft's assets/uris. Some time ago, it was there immediately after nft creation, but they've added performance optimizations.

I mean they will create the metadata object. The path will stay in the attributes.

**Comment by borispoehland** [comment]
Thank you so much for all your help 🎉😄
